### ISSUE TITLE
import _pickle

### ISSUE THREAD

**Issue by emmedve1** [dcoles/pytrace#2]
Same versions on Linux -> same symptom

> PS ~/upstream/snaketrace> python --version
> Python 3.9.0a5
> PS ~/upstream/snaketrace> git describe --tags
> v0.3.0-1-gdcf6ba4
> PS ~/upstream/snaketrace> echo "from _pickle import PickleBuffer" > py.py
> PS ~/upstream/snaketrace> python -m snaketrace py.py
> open('py.py', 'r', 32896)
> open('C:\\Users\\e.medve\\upstream\\snaketrace\\py.py', 'r', 32896)
> open('C:\\Users\\e.medve\\upstream\\snaketrace\\py.py', 'r', 32896)
> compile(b'from _pickle import PickleBuffer\r\n', 'py.py')
> exec(<code object <module> at 0x000001A08D2C3EA0, file "py.py", line 1>)
> import('_pickle', None, ['C:\\Users\\e.medve\\upstream\\snaketrace', 'C:\\Program Files\\Python3\\python39.zip', 'C:\\Program Files\\Python3\\DLLs', 'C:\\Program Files\\Python3\\lib', 'C:\\Program Files\\Python3', 'C:\\Program Files\\Python3\\lib\\site-packages'], [<class '_frozen_importlib.BuiltinImporter'>, <class '_frozen_importlib.FrozenImporter'>, <class '_frozen_importlib_external.PathFinder'>], [<class 'zipimport.zipimporter'>, <function FileFinder.path_hook.<locals>.path_hook_for_FileFinder at 0x000001A08B141D30>])
> import('_compat_pickle', None, ['C:\\Users\\e.medve\\upstream\\snaketrace', 'C:\\Program Files\\Python3\\python39.zip', 'C:\\Program Files\\Python3\\DLLs', 'C:\\Program Files\\Python3\\lib', 'C:\\Program Files\\Python3', 'C:\\Program Files\\Python3\\lib\\site-packages'], [<class '_frozen_importlib.BuiltinImporter'>, <class '_frozen_importlib.FrozenImporter'>, <class '_frozen_importlib_external.PathFinder'>], [<class 'zipimport.zipimporter'>, <function FileFinder.path_hook.<locals>.path_hook_for_FileFinder at 0x000001A08B141D30>])
> open('C:\\Program Files\\Python3\\lib\\__pycache__\\_compat_pickle.cpython-39.pyc', 'r', 32896)
> exec(<code object <module> at 0x000001A08D2CB240, file "C:\Program Files\Python3\lib\_compat_pickle.py", line 9>)
> builtins.id(1789074909600)
> open('C:\\Users\\e.medve\\upstream\\snaketrace\\snaketrace\\trace.py', 'r', 32896)
> open('C:\\Program Files\\Python3\\lib\\runpy.py', 'r', 32896)
> open('py.py', 'r', 32896)
> Traceback (most recent call last):
>   File "C:\Users\e.medve\upstream\snaketrace\snaketrace\trace.py", line 71, in trace
>     runpy.run_path(name, globals_, run_name='__main__')
>   File "C:\Program Files\Python3\lib\runpy.py", line 265, in run_path
>     return _run_module_code(code, init_globals, run_name,
>   File "C:\Program Files\Python3\lib\runpy.py", line 97, in _run_module_code
>     _run_code(code, mod_globals, init_globals,
>   File "C:\Program Files\Python3\lib\runpy.py", line 87, in _run_code
>     exec(code, run_globals)
>   File "py.py", line 1, in <module>
>     from _pickle import PickleBuffer
> KeyError: '_compat_pickle'
> cpython._PySys_ClearAuditHooks()

**Comment by dcoles** [comment]
@emmedve1 Thank you for the bug report!

I can reproduce this on a Python script that simply imports `pickle`, so that's definately not acceptable.

My suspicion is that `_compat_pickle` has been loaded as an indirect dependency of `runpy`, so when we clear `sys.modules` prior to running the target, it ends up in a weird "imported but not in `sys.modules` state.

Will look into ways to address this.

**Comment by dcoles** [comment]
Right. So it appears to be due to us replacing the `sys.modules` dict rather than updating it. Python still has the reference to the old one.

A quick fix is to change https://github.com/dcoles/snaketrace/blob/dcf6ba4fe6b37f975c490b9b69a80fe14bff14e0/snaketrace/trace.py#L57 to the following:
```python
sys.modules.clear()
sys.modules.update(MODULES)
```

Will test the changes and make a new release shortly.

**Comment by emmedve1** [comment]
Hello @dcoles,

> I can reproduce this on a Python script that simply imports pickle, so that's definitely not acceptable.

Copied the test case from the 'pickle' implementation from a desire to narrow the issue a bit

> Will test the changes and make a new release shortly.

Thanks for your time dude :-)

Cheers,

**Comment by dcoles** [comment]
> Thanks for your time dude :-)

No worries! Thanks for taking the time to report the bug!

Fix included in [`snaketrace-0.3.1`](https://pypi.org/project/snaketrace/0.3.1/).

**Comment by emmedve1** [comment]
> Fix included in snaketrace-0.3.1

Looks good. Thanks again :-)
